import { IndustryTemplate } from "./types";

export const INDUSTRY_TEMPLATES: IndustryTemplate[] = [
  {
    id: "duocsi_nhathuoc",
    name: "Nhà thuốc / Dược sĩ",
    description: "Tối ưu hóa các bài chia sẻ kiến thức y tế, chăm sóc sức khỏe, nâng uy tín chuyên môn của dược sĩ.",
    formData: {
      brandName: "Dược sĩ Ngoan",
      userRole: "Dược sĩ tư vấn chính tại Nhà thuốc An Tâm",
      industry: "Dược phẩm, Thực phẩm bảo vệ sức khỏe & Nhà thuốc",
      nicheTopic: "Viết content chia sẻ kiến thức sức khỏe & tư vấn sử dụng thuốc",
      experienceYears: "15 năm",
      mainProduct: "Các dòng sản phẩm men vi sinh nhập khẩu, sữa dĩnh dưỡng chất lượng cao, thực phẩm bổ sung sức khỏe",
      strengths: "Có chuyên môn thực tế cao, tận tâm chu đáo, hiểu tường tận cơ chế bệnh lý, hướng dẫn dùng thuốc an toàn, khoa học",
      goals: ["Viết bài Facebook", "Tạo ý tưởng video", "Viết kịch bản video ngắn", "Chăm sóc khách hàng", "Viết bài chia sẻ kiến thức"],
      mainPlatform: "Facebook cá nhân",
      targetAudience: "Mẹ bỉm sữa chăm con hay ốm vặt, người trưởng thành quan tâm sức khỏe gia đình, người lớn tuổi có bệnh lý nền",
      customerPainPoints: "Trẻ lười ăn, chậm lớn, hay đi ngoài; người lớn dễ bị lạm dụng kháng sinh hoặc mua thuốc sai liều lượng; thiếu thông tin chăm sóc đúng cách.",
      customerDesires: "Có giải pháp hỗ trợ chăm sóc sức khỏe an toàn, không phụ thuộc kháng sinh, phục hồi cơ địa tự nhiên, tư vấn từ chuyên gia có tâm.",
      customerBarriers: "Sợ hàng giả, sợ tác dụng phụ của thuốc tây, hoang mang trước quá nhiều luồng thông tin trên mạng xã hội.",
      customerMisconceptions: "Cứ con hắt hơi sổ mũi là mua kháng sinh ngay; uống thuốc bổ càng nhiều càng tốt; nghĩ chỉ cần mua thuốc đắt tiền là khỏi bệnh.",
      toneOfVoice: "Có chuyên môn nhưng dễ hiểu",
      addressingStyle: "Dược sĩ - anh/chị",
      requiredFormats: ["Bài Facebook", "Kịch bản video ngắn", "Caption", "Bài chia sẻ kiến thức", "Tin nhắn chăm sóc khách hàng"],
      mustHaves: "Luôn nhấn mạnh tính an toàn, khoa học, có lời khuyên thay đổi lối sống, thói quen ăn uống lành mạnh cốt lõi.",
      thingsToAvoid: "Không cam kết chắc chắn hết bệnh 100%, không nói quá công dụng, không khuyên ngưng điều trị theo y lệnh bác sĩ.",
      forbiddenKeywords: "Chữa khỏi hoàn toàn, dứt điểm, cam kết khỏi 100%, trị tận gốc, thuốc thần kỳ, đảm bảo hết bệnh",
      replacementKeywords: "Hỗ trợ cải thiện dần, góp phần chăm sóc cơ thể, giải pháp hỗ trợ an toàn, hướng chăm sóc đúng cách tại nhà"
    }
  },
  {
    id: "me_va_be",
    name: "Mẹ và Bé",
    description: "Tập trung giải quyết nỗi lo nuôi con nhỏ, chia sẻ kinh nghiệm bỉm sữa, dinh dưỡng, giáo dục sớm cho trẻ.",
    formData: {
      brandName: "Mommy Care Store",
      userRole: "Chủ shop & Chuyên viên tư vấn dinh dưỡng mẹ bé",
      industry: "Bán lẻ sản phẩm Mẹ & Bé, đồ dùng sơ sinh và dinh dưỡng trẻ em",
      nicheTopic: "Kịch bản video ngắn và chia sẻ kinh nghiệm chăm con khoa học",
      experienceYears: "10 năm",
      mainProduct: "Sữa công thức cao cấp, bỉm hữu cơ, vitamin tổng hợp cho bé, đồ dùng sơ sinh an toàn cho da nhạy cảm",
      strengths: "Đã đồng hành cùng hàng ngàn mẹ bỉm sữa vượt qua giai đoạn khủng hoảng, cung cấp sản phẩm nhập khẩu chính ngạch có kiểm định rõ ràng",
      goals: ["Tạo ý tưởng video", "Viết kịch bản video ngắn", "Viết bài Facebook", "Phân tích insight khách hàng", "Lên kế hoạch content"],
      mainPlatform: "TikTok",
      targetAudience: "Mẹ bầu, mẹ bỉm sữa nuôi con từ sơ sinh đến 5 tuổi, lần đầu làm mẹ chưa có nhiều kinh nghiệm",
      customerPainPoints: "Con biếng ăn, hay khóc đêm, đề kháng kém; mẹ bị stress rụng tóc sau sinh; không biết lựa chọn sản phẩm nào an toàn thật sự giữa thiên đường hàng nhái.",
      customerDesires: "Nuôi con nhẹ nhàng, con khỏe mạnh tăng cân đều, học hỏi được phương pháp ăn dặm hay chăm sóc giấc ngủ đúng chuẩn khoa học.",
      customerBarriers: "Lo sợ sản phẩm chứa chất độc hại, giá thành cao so với tài chính, nhận nhiều ý kiến trái chiều từ gia đình (mẹ chồng - nàng dâu).",
      customerMisconceptions: "Cứ bé bụ bẫm mới là khỏe mạnh; ép con ăn bằng mọi cách; mua đồ sơ sinh giá rẻ tràn lan trên mạng xã hội không có nguồn gốc.",
      toneOfVoice: "Gần gũi",
      addressingStyle: "Cô - các mẹ",
      requiredFormats: ["Kịch bản video ngắn", "Bài Facebook", "Caption", "Hook mở đầu", "CTA"],
      mustHaves: "Lời khuyên thực tế từ mẹ bỉm thực chiến, trích dẫn kiến thức nhi khoa uy tín nhưng nói bằng ngôn ngữ dí dỏm, thông thoáng.",
      thingsToAvoid: "Không công kích cách nuôi con truyền thống của các ông bà quá gay gắt, không dọa dẫm khiến mẹ bỉm hoảng sợ tột độ.",
      forbiddenKeywords: "Tuyệt đối an toàn, cải thiện ngay tức thì, đặc trị dứt điểm, không tác dụng phụ, thần dược chăm con",
      replacementKeywords: "Hỗ trợ nuôi con khỏe hơn, đồng hành cùng các mẹ, giải pháp từ tự nhiên lành tính, hỗ trợ cải thiện tiêu hóa lành mạnh"
    }
  },
  {
    id: "xuong_khop",
    name: "Xương Khớp",
    description: "Đồng cảm nỗi đau mỏi gối, đau lưng của tuổi trung niên và cao niên, đề xuất lối sống vận động kết hợp bổ trợ.",
    formData: {
      brandName: "Khớp An Tâm Center",
      userRole: "Chuyên viên vật lý trị liệu & tư vấn phục hồi xương khớp",
      industry: "Y học cổ truyền, Vật lý trị liệu & Thực phẩm hỗ trợ cơ xương khớp",
      nicheTopic: "Viết content Facebook & video hướng dẫn bài tập giảm đau tại nhà",
      experienceYears: "20 năm",
      mainProduct: "Khóa học bài tập trị liệu khớp gối, sữa hạt chuyên biệt cho xương khớp bổ sung canxi và Glucosamine",
      strengths: "Kinh nghiệm thực hành trị liệu lâm sàng, giáo trình tập luyện đơn giản hiệu quả cao, tư vấn cá nhân hóa từng trạng thái bệnh",
      goals: ["Viết bài bán hàng", "Viết bài Facebook", "Xây dựng thương hiệu cá nhân", "Tạo ý tưởng video", "Tư vấn khách hàng"],
      mainPlatform: "Facebook cá nhân",
      targetAudience: "Người trung niên từ 45-65 tuổi bị thoái hóa khớp gối, thoát vị đĩa đệm, đau mỏi vai gáy do tính chất công việc hoặc lão hóa",
      customerPainPoints: "Đau buốt mỗi khi thay đổi thời tiết, đi lại khó khăn, mất ngủ vì đau nhức, sợ viễn cảnh phải nằm một chỗ làm phiền con cháu.",
      customerDesires: "Khung xương chắc khỏe linh hoạt, đi lại không đau đớn, ngủ ngon giấc, duy trì niềm vui tuổi già tự chủ không phụ thuộc.",
      customerBarriers: "Đã thử nhiều loại thuốc nam, gội đầu bấm huyệt, thuốc đông y gia truyền trôi nổi nhưng không đỡ, sinh ra tâm lý mất niềm tin và sợ tốn kém vô ích.",
      customerMisconceptions: "Đau khớp là phải nằm yên tuyệt đối không được vận động; uống thuốc giảm đau liên tục để cắt cơn đau nhanh; nghĩ thoái hóa là hết cách phục hồi.",
      toneOfVoice: "Truyền cảm hứng",
      addressingStyle: "Em - anh/chị",
      requiredFormats: ["Bài Facebook", "Kịch bản video ngắn", "Bài bán hàng", "Bài chia sẻ kiến thức", "Tin nhắn chốt sale"],
      mustHaves: "Nêu bật tầm quan trọng của việc kết hợp giữa vận động trị liệu nhẹ nhàng và bổ sung dinh dưỡng đúng cách.",
      thingsToAvoid: "Không cam kết uống là khỏi vĩnh viễn, không dùng hình ảnh mô tả bệnh tật rùng rợn dọa dẫm thái quá.",
      forbiddenKeywords: "Trị dứt hoàn toàn, chữa khỏi 100%, không còn đau đớn vĩnh viễn, trị tận gốc rễ thoái hóa, cam kết dứt điểm",
      replacementKeywords: "Góp phần giảm bớt cơn đau, hỗ trợ vận động linh hoạt hơn, đồng hành phục hồi tích cực, giải pháp bổ dưỡng cho sụn khớp"
    }
  },
  {
    id: "spa_lamdep",
    name: "Spa / Làm đẹp",
    description: "Tập trung vào hành trình trẻ hóa, trị mụn, trị nám, mang lại sự tự tin thanh xuân cho phụ nữ công sở.",
    formData: {
      brandName: "Thanh Thủy Beauty Center",
      userRole: "Founder & Chuyên gia da liễu thẩm mỹ",
      industry: "Dịch vụ Spa, điều trị da công nghệ cao & chăm sóc sắc đẹp",
      nicheTopic: "Viết kịch bản video chia sẻ quy trình skincare chuẩn y khoa và quảng bá gói liệu trình",
      experienceYears: "10 năm",
      mainProduct: "Cáp dịch vụ trị mụn chuẩn y khoa, cấy collagen tươi căng bóng da, điều trị sẹo rỗ cam kết theo phác đồ",
      strengths: "Hệ thống trang thiết bị chuyển giao công nghệ chính hãng châu Âu, kỹ thuật viên đào tạo khắt khe, chính sách bảo hành da rõ ràng bằng văn bản",
      goals: ["Tạo ý tưởng video", "Viết kịch bản video ngắn", "Viết bài Facebook", "Viết bài bán hàng", "Xây dựng thương hiệu cá nhân"],
      mainPlatform: "TikTok",
      targetAudience: "Phụ nữ văn phòng từ 22-45 tuổi gánh chịu áp lực công việc khiến da sạm, mụn ẩn dài ngày, xuất hiện dấu hiệu lão hóa sớm.",
      customerPainPoints: "Tự ti vì khuôn mặt mẩn mụn, thâm sạm khi gặp đối tác; đã bỏ hàng chục triệu mua mỹ phẩm đắt tiền nhưng càng dùng càng kích ứng.",
      customerDesires: "Sở hữu làn da căng mướt mộc khỏe mạnh, láng mịn tự tin để mặt mộc vẫn rạng ngời, được chăm sóc bởi chuyên gia đáng tin cậy.",
      customerBarriers: "Sợ các cơ sở spa 'chui' sử dụng kem trộn, sợ đau đớn khi thực hiện liệu trình hoặc bị chèo kéo mua gói dịch vụ cao ngất ngưỡng tại chỗ.",
      customerMisconceptions: "Làm sạch qua loa bằng nước là đủ; mụn tự hết khi lớn lên; nghĩ rằng đi spa một buổi là da đẹp trọn đời không cần chăm tại nhà nữa.",
      toneOfVoice: "Sang trọng",
      addressingStyle: "Chuyên gia - khách hàng",
      requiredFormats: ["Kịch bản video ngắn", "Bài bán hàng", "Hook mở đầu", "CTA", "Kịch bản livestream"],
      mustHaves: "Luôn lồng ghép tính khoa học, soi cấu trúc da thực tế, hình ảnh trước/sau điều trị chân thực chất lượng cao.",
      thingsToAvoid: "Không dọa nạt thái quá, không dùng ngôn từ tâng bốc dịch vụ quá lố kiểu thần thánh hóa.",
      forbiddenKeywords: "Đẹp ngay sau 60 phút, trắng vĩnh viễn, cam kết sạch mụn hoàn toàn, không bao giờ tái phát, tái sinh 100%",
      replacementKeywords: "Dần cải thiện sắc tố, làm sạch sâu thông thoáng nền da, hỗ trợ nuôi dưỡng da khỏe từ tế bào, hồi phục độ ẩm tự nhiên"
    }
  },
  {
    id: "bat_dong_san",
    name: "Bất động sản",
    description: "Chia sẻ bài học đầu tư an toàn, tư vấn căn hộ an cư phù hợp tầm tài chính, phân tích thị trường thực chiến.",
    formData: {
      brandName: "Đông Tây Land - Đất Nền Thực Chiến",
      userRole: "Nhà môi giới bất động sản chuyên nghiệp & Chuyên gia định giá đất nền",
      industry: "Môi giới Bất động sản, đất nền vùng ven và căn hộ cao cấp",
      nicheTopic: "Xây dựng thương hiệu cá nhân, phân tích bài toán tài chính mua nhà/đất",
      experienceYears: "10 năm",
      mainProduct: "Sản phẩm đất nền phân lô sổ đỏ ven sông, căn hộ chung cư cao cấp vùng nội đô trả góp lãi suất ưu đãi",
      strengths: "Nắm vững pháp lý dự án quy hoạch, có nguồn hàng độc quyền giá tốt trực tiếp từ chủ đầu tư, hỗ trợ thủ tục sang tên sổ đỏ trọn gói",
      goals: ["Xây dựng thương hiệu cá nhân", "Viết bài Facebook", "Tạo ý tưởng video", "Viết kịch bản video ngắn", "Phân tích khách hàng"],
      mainPlatform: "Facebook cá nhân",
      targetAudience: "Cặp vợ chồng trẻ muốn mua căn hộ đầu đời tích lũy an cư; nhà đầu tư cá nhân có dòng vốn nhàn rỗi muốn tìm nơi trú ẩn dòng tiền an toàn.",
      customerPainPoints: "Sợ dính quy hoạch treo, sợ mua phải dự án không ra được sổ đỏ, lo lắng gánh nặng trả góp lãi suất thả nổi khi hết ưu đãi tài chính.",
      customerDesires: "Tìm được đúng tài sản có khả năng tăng trưởng bền vững, thủ tục pháp lý sạch sẽ gãy gọn, phương thức thanh toán giãn chia nhỏ nhẹ nhàng.",
      customerBarriers: "Không tin tưởng các 'cò đất' nói năng khoa trương thiếu thực tế; thị trường đang có nhiều biến động lạm phát khó đoán định định giá.",
      customerMisconceptions: "Mua nhà đất lúc nào cũng có lãi ngay lập tức; nghĩ chỉ cần có vốn tự có 100% tài chính mới dám mua nhà an cư.",
      toneOfVoice: "Chuyên gia",
      addressingStyle: "Tôi – bạn",
      requiredFormats: ["Bài Facebook", "Kịch bản video ngắn", "Bài chia sẻ kiến thức", "Hook mở đầu", "CTA"],
      mustHaves: "Phân tích các con số tài chính cụ thể, cung cấp quy trình check pháp lý minh bạch trước khi giao dịch.",
      thingsToAvoid: "Không hứa hẹn tỷ suất sinh lời quá ảo (ví dụ: nhân đôi tài khoản sau vài tháng), không giấu giếm các điểm hạn chế của dự án.",
      forbiddenKeywords: "Chắc chắn lãi gấp đôi, siêu lợi nhuận, cam kết sinh lời 100%, độc quyền duy nhất rẻ nhất thế giới, mua là giàu ngay",
      replacementKeywords: "Tiềm năng thanh khoản tốt, dòng tiền tăng trưởng kỳ vọng ổn định, thông tin minh bạch, giải pháp an cư phù hợp tài chính"
    }
  },
  {
    id: "giao_duc_daotao",
    name: "Giáo dục / Đào tạo",
    description: "Nhấn mạnh vào kỹ năng thực chiến, định hướng tư duy ứng dụng và thay đổi cuộc đời thông qua tri thức thực chất.",
    formData: {
      brandName: "Học Viện Kỹ Năng Số DigiEdu",
      userRole: "Giảng viên - Chuyên gia đào tạo kỹ năng Content Marketing",
      industry: "Giáo dục, Đào tạo trực tuyến & Phát triển kỹ năng chuyên môn",
      nicheTopic: "Viết bài chia sẻ tư duy làm nghề Content, kế hoạch tuyển sinh lớp học",
      experienceYears: "10 năm",
      mainProduct: "Khóa đào tạo Content Marketing đa kênh từ con số 0 đến có thu nhập ổn định",
      strengths: "Phương pháp giảng dạy cầm tay chỉ việc, bài tập thực tế sửa chi tiết 1-1, mạng lưới hỗ trợ kết nối đối tác tuyển dụng ngay sau khóa học",
      goals: ["Xây dựng thương hiệu cá nhân", "Viết bài Facebook", "Viết bài bán hàng", "Tạo ý tưởng video", "Đào tạo đội nhóm"],
      mainPlatform: "Facebook cá nhân",
      targetAudience: "Sinh viên mới ra trường mông lung hướng đi; nhân sự chuyển ngành từ kế toán, hành chính sang lĩnh vực sáng tạo nội dung.",
      customerPainPoints: "Học lý thuyết suông trên trường không áp dụng được vào công việc thực tế, loay hoay viết mãi không ai đọc, không biết cách tìm job ngoài kiếm thêm thu nhập.",
      customerDesires: "Có một kỹ năng nghề nghiệp vững vàng được xã hội công nhận, tự tin ứng tuyển vị trí Content Manager, nhận job tự do có thu nhập tốt thoải mái thời gian.",
      customerBarriers: "Sợ các trung tâm lừa đảo dạy lý thuyết rác, lo lắng bản thân không có năng khiếu viết lách thì không thể làm được nghề sáng tạo.",
      customerMisconceptions: "Làm content là phải có hoa tay văn chương bẩm sinh; nghĩ viết càng dài bay bổng hoa mỹ mới là content chất lượng thực sự.",
      toneOfVoice: "Có chuyên môn nhưng dễ hiểu",
      addressingStyle: "Mình – bạn",
      requiredFormats: ["Bài Facebook", "Bài chia sẻ kiến thức", "Bài bán hàng", "Lịch content", "Kế hoạch đào tạo"],
      mustHaves: "Luôn lồng ghép case-study học viên cũ từ số 0 đạt kết quả thật để tạo động lực, hướng dẫn các mẹo thực hành miễn phí trước.",
      thingsToAvoid: "Không dùng từ ngữ quá hàn lâm hàn việt hoa mỹ, không cam kết học xong là chắc chắn lương chục triệu ngay lập tức.",
      forbiddenKeywords: "Cam kết bao đỗ 100%, có việc ngay lập tức, làm giàu nhanh, trở thành master sau 3 buổi, cam kết hoàn tiền vô điều kiện",
      replacementKeywords: "Rèn luyện kỹ năng thực tế, lộ trình từng bước từ căn bản, đồng hành hỗ trợ sửa bài, cơ hội nâng cao thu nhập thực chất"
    }
  },
  {
    id: "kinh_doanh_online",
    name: "Kinh doanh online",
    description: "Hướng dẫn khởi nghiệp kinh doanh không vốn lớn, các mẹo bán hàng đa kênh thực chiến hiệu quả.",
    formData: {
      brandName: "Học Viện Khởi Nghiệp Tự Do",
      userRole: "Nhà đào tạo & Mentor hỗ trợ khởi nghiệp bán hàng online",
      industry: "Kinh doanh kỹ thuật số, Bán lẻ đa kênh và Đào tạo kinh doanh",
      nicheTopic: "Kinh nghiệm thực chiến bán hàng vạn đơn không cần vốn khủng",
      experienceYears: "10 năm",
      mainProduct: "Khóa học chiến lược phân tích sản phẩm hot trend & kỹ thuật tối ưu gian hàng Shopee/TikTok Shop",
      strengths: "Sở hữu kho xưởng nguồn hàng sỉ tận gốc giá rẻ nhất, đội ngũ supporter kỹ thuật hỗ trợ cài đặt gian hàng trọn gói",
      goals: ["Tạo ý tưởng video", "Viết kịch bản video ngắn", "Đào tạo đội nhóm", "Lên kế hoạch content", "Chốt sale"],
      mainPlatform: "TikTok",
      targetAudience: "Mẹ bỉm sữa, dân văn phòng rảnh rỗi muốn kiếm thêm thu nhập 5-10 triệu mỗi tháng từ việc bán hàng online rảnh tay.",
      customerPainPoints: "Không biết chọn nguồn hàng chất lượng ở đâu, sợ ôm hàng tồn kho lỗ vốn, mù tịt công nghệ không biết làm video xây kênh bán hàng.",
      customerDesires: "Có một quy trình bán hàng khép kín tự vận hành tinh gọn, tạo lập nguồn thu nhập thụ động bền vững cho gia đình.",
      customerBarriers: "Sợ thất bại mất tiền oan, tự ti vì rụt rè không dám xuất hiện livestream nói chuyện trước máy quay ống kính máy ảnh.",
      customerMisconceptions: "Kinh doanh online là phải cần vốn hàng trăm triệu; nghĩ đơn thuần chỉ cần đăng bài lên trang cá nhân là tự khắc có người vào mua ngay.",
      toneOfVoice: "Thực chiến",
      addressingStyle: "Tôi – bạn",
      requiredFormats: ["Kịch bản video ngắn", "Bài bán hàng", "CTA", "Kịch bản livestream", "Tin nhắn chốt sale"],
      mustHaves: "Checklist hành động 1-2-3 đơn giản cụ thể, giải thích các thuật ngữ chuyển đổi, tỷ lệ click bằng tiếng Việt bình dân nhất.",
      thingsToAvoid: "Không khoe khoang doanh thu tiền tỷ ảo khiến người khác mất thói quen làm việc thực chất, không vẽ ra viễn cảnh giàu nhanh không làm cũng có ăn.",
      forbiddenKeywords: "Cam kết giàu sau 1 tháng, kiếm tiền cực dễ, không làm cũng có tiền, cơ hội tỷ phú độc nhất vô nhị, lãi khủng ngay",
      replacementKeywords: "Từng bước tối ưu quy trình, giải bài toán nguồn vốn nhỏ, nỗ lực tạo kết quả thật, xây dựng nền móng kinh doanh an toàn"
    }
  },
  {
    id: "thuong_hieu_canhan",
    name: "Thương hiệu cá nhân",
    description: "Định vị giá trị cốt lõi cá nhân, đúc rút bài học sâu sắc từ cuộc sống, thu hút khách hàng trung thành nhờ sự uy tín chân thật.",
    formData: {
      brandName: "Coach Nguyễn Hoàng - Tư Duy Thịnh Vượng",
      userRole: "Khai vấn viên cuộc sống & Chuyên gia xây dựng thương hiệu cá nhân",
      industry: "Life Coaching, Tư vấn phát triển bản thân & Đào tạo định vị thương hiệu",
      nicheTopic: "Viết bài chia sẻ bài học cuộc sống, đúc rút kinh nghiệm làm nghề tâm huyết",
      experienceYears: "15 năm",
      mainProduct: "Gói khai vấn 1-1 thiết kế bản đồ định vị cuộc đời và khai phá tiềm năng lãnh đạo",
      strengths: "Đã lắng nghe và hỗ trợ chuyển hóa cuộc đời cho hơn 500 cá nhân, kỹ năng thấu cảm lắng nghe sâu sắc không phán xét",
      goals: ["Xây dựng thương hiệu cá nhân", "Viết bài Facebook", "Tạo ý tưởng video", "Viết bài chia sẻ kiến thức", "Lên kế hoạch content"],
      mainPlatform: "Facebook cá nhân",
      targetAudience: "Quản lý cấp trung, chuyên gia tự do (freelancer) muốn định vị giá trị của mình rõ ràng hơn để nhận cơ hội lớn.",
      customerPainPoints: "Mông lung không biết thế mạnh thực sự của bản thân là gì, e ngại xuất hiện tự quảng bá mình, viết bài trên mạng xã hội thấy giả tạo gượng gạo.",
      customerDesires: "Sống đúng với giá trị thực chất của mình, được cộng đồng tôn trọng tin yêu nhiệt thành, tạo dựng sự ảnh hưởng tự nhiên giúp thu hút khách hàng tự đến.",
      customerBarriers: "Sợ bị dán nhãn là 'phét lác', 'lùa gà' hay làm màu quá lố trên mạng xã hội; thiếu sự kiên trì bền bỉ khi viết bài thời gian đầu ít tương tác.",
      customerMisconceptions: "Cho rằng chỉ người nổi tiếng showbiz mới cần xây dựng thương hiệu cá nhân; nghĩ phải viết bài phô vẽ sự giàu sang mới là thu hút.",
      toneOfVoice: "Truyền cảm hứng",
      addressingStyle: "Tôi – bạn",
      requiredFormats: ["Bài Facebook", "Bài chia sẻ kiến thức", "Hook mở đầu", "CTA", "Caption"],
      mustHaves: "Hành văn tinh ý đi sâu vào nội tâm, chia sẻ góc khuất thất bại chân thành trước khi đúc rút bài học thành công vinh quang.",
      thingsToAvoid: "Không hô hào khẩu hiệu sáo rỗng thiếu thực tế, tránh phê phán gay gắt hay tạo drama thu hút tương tác bẩn.",
      forbiddenKeywords: "Tuyệt đối hoàn mỹ, cam kết thay đổi vận mệnh ngay, bí quyết độc nhất vô nhị, chữa lành 100%, bậc thầy tối thượng",
      replacementKeywords: "Đồng hành khám phá bản thân, từng bước chuyển hóa nội tâm, nâng cao giá trị thực chất, tìm lại sự tự tin bên trong"
    }
  }
];
